// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: lineProcessor.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sports  []string `protobuf:"bytes,1,rep,name=sports,proto3" json:"sports,omitempty"`
	TimeUpd string   `protobuf:"bytes,2,opt,name=timeUpd,proto3" json:"timeUpd,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineProcessor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_lineProcessor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_lineProcessor_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetSports() []string {
	if x != nil {
		return x.Sports
	}
	return nil
}

func (x *Request) GetTimeUpd() string {
	if x != nil {
		return x.TimeUpd
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resp []*Response_Line `protobuf:"bytes,1,rep,name=resp,proto3" json:"resp,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineProcessor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_lineProcessor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_lineProcessor_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetResp() []*Response_Line {
	if x != nil {
		return x.Resp
	}
	return nil
}

type Response_Line struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Response_Line) Reset() {
	*x = Response_Line{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lineProcessor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Line) ProtoMessage() {}

func (x *Response_Line) ProtoReflect() protoreflect.Message {
	mi := &file_lineProcessor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Line.ProtoReflect.Descriptor instead.
func (*Response_Line) Descriptor() ([]byte, []int) {
	return file_lineProcessor_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Response_Line) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Response_Line) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_lineProcessor_proto protoreflect.FileDescriptor

var file_lineProcessor_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x22, 0x66, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x72, 0x65, 0x73, 0x70, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x04, 0x72, 0x65, 0x73, 0x70, 0x1a,
	0x30, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x32, 0x4a, 0x0a, 0x0d, 0x4c, 0x69, 0x6e, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x6f, 0x72, 0x12, 0x39, 0x0a, 0x16, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4f,
	0x6e, 0x53, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x4c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x0e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lineProcessor_proto_rawDescOnce sync.Once
	file_lineProcessor_proto_rawDescData = file_lineProcessor_proto_rawDesc
)

func file_lineProcessor_proto_rawDescGZIP() []byte {
	file_lineProcessor_proto_rawDescOnce.Do(func() {
		file_lineProcessor_proto_rawDescData = protoimpl.X.CompressGZIP(file_lineProcessor_proto_rawDescData)
	})
	return file_lineProcessor_proto_rawDescData
}

var file_lineProcessor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lineProcessor_proto_goTypes = []interface{}{
	(*Request)(nil),       // 0: proto.Request
	(*Response)(nil),      // 1: proto.Response
	(*Response_Line)(nil), // 2: proto.Response.Line
}
var file_lineProcessor_proto_depIdxs = []int32{
	2, // 0: proto.Response.resp:type_name -> proto.Response.Line
	0, // 1: proto.LineProcessor.SubscribeOnSportsLines:input_type -> proto.Request
	1, // 2: proto.LineProcessor.SubscribeOnSportsLines:output_type -> proto.Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lineProcessor_proto_init() }
func file_lineProcessor_proto_init() {
	if File_lineProcessor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lineProcessor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineProcessor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lineProcessor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_Line); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lineProcessor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lineProcessor_proto_goTypes,
		DependencyIndexes: file_lineProcessor_proto_depIdxs,
		MessageInfos:      file_lineProcessor_proto_msgTypes,
	}.Build()
	File_lineProcessor_proto = out.File
	file_lineProcessor_proto_rawDesc = nil
	file_lineProcessor_proto_goTypes = nil
	file_lineProcessor_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// LineProcessorClient is the client API for LineProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LineProcessorClient interface {
	SubscribeOnSportsLines(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type lineProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewLineProcessorClient(cc grpc.ClientConnInterface) LineProcessorClient {
	return &lineProcessorClient{cc}
}

func (c *lineProcessorClient) SubscribeOnSportsLines(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.LineProcessor/SubscribeOnSportsLines", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LineProcessorServer is the server API for LineProcessor service.
type LineProcessorServer interface {
	SubscribeOnSportsLines(context.Context, *Request) (*Response, error)
}

// UnimplementedLineProcessorServer can be embedded to have forward compatible implementations.
type UnimplementedLineProcessorServer struct {
}

func (*UnimplementedLineProcessorServer) SubscribeOnSportsLines(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscribeOnSportsLines not implemented")
}

func RegisterLineProcessorServer(s *grpc.Server, srv LineProcessorServer) {
	s.RegisterService(&_LineProcessor_serviceDesc, srv)
}

func _LineProcessor_SubscribeOnSportsLines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LineProcessorServer).SubscribeOnSportsLines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LineProcessor/SubscribeOnSportsLines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LineProcessorServer).SubscribeOnSportsLines(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _LineProcessor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LineProcessor",
	HandlerType: (*LineProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubscribeOnSportsLines",
			Handler:    _LineProcessor_SubscribeOnSportsLines_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lineProcessor.proto",
}
